baseURL = "https://satvikk.github.io/" 
languageCode = "en-us" 
title = "Satvik Kishore" 
theme = "ananke" 

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Satvik Kishore"
    description = "Something about me"
    github = "https://github.com/satvikk"
    twitter = "https://twitter.com/SatvikKishore"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"